version: "3"
services:
  back:
    build: ./back
    container_name: digikofy-back-container
    ports:
      - "8000:8000"
    environment: 
      PORT : 8000
    healthcheck:
      test: curl --fail -s http://localhost:8000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  front:
    build: ./front
    container_name: digikofy-front-container
    ports: 
      - "3000:3000"
    environment: 
      PORT : 3000

  test:
    build: ./back
    container_name: digikofy-test-container
    command: ["pytest", "./app/tests/test_api.py"]
    


    