version: "3"
services:
  back:
    build: ./back
    container_name: digikofy-back-container
    ports:
      - "8000:8000"
    environment: 
      PORT : 8000
    command: ["pytest","./tests/test_api.py"]

  front:
    build: ./front
    container_name: digikofy-front-container
    ports: 
      - "3000:3000"
    environment: 
      PORT : 3000
    